name: C/C++ CI

permissions:
  contents: write
  issues: write

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          version: '7.0.0' # Specify the MinGW version here

      - name: Verify MinGW Version
        run: |
          gcc --version
          g++ --version    

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
          cmake --build .

      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

      - name: Action For Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
